### ISSUE TITLE
Setting custom labels is not possible

### ISSUE THREAD

**Issue by kashkarik22i** [milvus-io/milvus-helm#161]
For our k8s set up we are required to add a custom label
```
labels:
  team: our_ai_team
```
to all team-owned resources.
Unfortunately the values are hardcoded [here](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/templates/_helpers.tpl#L77) and [here](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/templates/_helpers.tpl#L67)
like that:
```
{{/* Helm required labels */}}
{{- define "milvus.labels" -}}
helm.sh/chart: {{ include "milvus.chart" . }}
{{ include "milvus.matchLabels" . }}
{{- if or .Chart.AppVersion .Values.image.tag }}
app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}

{{/* matchLabels */}}
{{- define "milvus.matchLabels" -}}
app.kubernetes.io/name: {{ include "milvus.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
```

and then used e.g. [here](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/templates/writable-deployment.yaml#L6) or [here](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/templates/writable-deployment.yaml#L19)

like that
```
  template:
    metadata:
      labels:
{{ include "milvus.matchLabels" . | indent 8 }}
        component: "writable"
      annotations:
```

so I don't see an easy was of fixing it at the moment

**Comment by jeffoverflow** [comment]
We will fix this in a later release!

**Comment by VRudniev** [comment]
Hi @jeffoverflow, 

I've tried to add custom labels via podLabels as described in the documentation, but it only works for writable and readable deployments. I would like to know is there any way to do the same for the *-admin pod as well?
