### ISSUE TITLE
Failed to install app milvus.

### ISSUE THREAD

**Issue by mangopaq** [milvus-io/milvus-helm#167]
`Failed to install app milvus. Error: rendered manifests contain a resource that already exists. Unable to continue with install: Service "milvus" in namespace "milvus" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "milvus"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "milvus"`

**Comment by jeffoverflow** [comment]
First of all you need to make sure you've successfully uninstalled the helm `release`, before reinstalling.

To list all the releases, use:
`$ helm list --all --all-namespaces`

To uninstall a release, use:
`$ helm uninstall <release-name> -n <namespace>`

Sample:
`$ helm uninstall my-release -n milvus`

Now, try installing again.
