### ISSUE TITLE
unable to run milvus cluster with gpu image

### ISSUE THREAD

**Issue by becash143** [milvus-io/milvus-helm#169]
Error message : /var/lib/milvus/bin/milvus_server: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file too short

Used image tag : "0.10.0-gpu-d061620-5f3c00"

**Comment by jeffoverflow** [comment]
Good tutorial on this subject can be found [k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin) or [gpu-operator](https://nvidia.github.io/gpu-operator/)

**Comment by becash143** [comment]
nvidia-container-runtime solved the issue
