### ISSUE TITLE
In helm-chart 1.1.1, milvus version is 1.1.0

### ISSUE THREAD

**Issue by rky0930** [milvus-io/milvus-helm#181]
In tag milvus-1.1.1, milvus version is 1.1.0, when does the version name of helm-chart tag match with the version of milvus?

**Comment by jeffoverflow** [comment]
@rky0930 The helm chart tag is not associated with the milvus version.

**Comment by rky0930** [comment]
@jeffoverflow Thanks for the reply ! So what do tags mean?

**Comment by jeffoverflow** [comment]
> @jeffoverflow Thanks for the reply ! So what do tags mean?

@rky0930 The tags mean the version of chart.
