### ISSUE TITLE
milvus readonly stuck with this values: cluster.enabled=true with persistence.enabled=false

### ISSUE THREAD

**Issue by nmarandi** [milvus-io/milvus-helm#182]
when I install milvus with this command:
 `
helm install --set cluster.enabled=true --set cache.insertBufferSize=4GB --set cache.cacheSize=6GB --set metrics.enabled=true --set readonly.cache.insertBufferSize=2GB --set readonly.cache.cacheSize=5GB --set replicas=3 milvus  milvus/milvus
`
the milvus-readonly pod stuck in initializing.

**Comment by jeffoverflow** [comment]
@nmarandi  See: https://github.com/milvus-io/milvus-helm/tree/master/charts/milvus#deploying-milvus-with-cluster-enabled

**Comment by nmarandi** [comment]
> @nmarandi See: https://github.com/milvus-io/milvus-helm/tree/master/charts/milvus#deploying-milvus-with-cluster-enabled

Does it mean that I can't have a Milvus cluster without persistence volume?

**Comment by jeffoverflow** [comment]
@nmarandi Yes.
