### ISSUE TITLE
milvus-standalone fail

### ISSUE THREAD

**Issue by L-lei** [milvus-io/milvus-helm#201]
#### Environment:
- milvus-helm version(2.1.0):
- Deployment mode(standalone):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others: 

#### Additional context:
Milvus standalone doesn't just use one?
error info:
Warning  FailedScheduling  15h   default-scheduler  0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.

**Comment by jeffoverflow** [comment]
@L-lei  You need to check if the persistent volume claims is available.

**Comment by L-lei** [comment]
OK. Thanks very much for talking to me

**Comment by L-lei** [comment]
> @L-lei You need to check if the persistent volume claims is available.

The specified Minio of persistent volume needs to be created manually?

Persistent volume claims need to be created by yourself?

Or what kind of machine hardware configuration is required to install Milvus

**Comment by zwd1208** [comment]
@L-lei  If you want to use existing pvc for minio, you can use --set minio.persistence.existingClaim=<your_pvc>.  this pvc needs to be created before install. 
By default, install Milvus and Minio will automatic use default storageClass to create pvc.
No specific hardware configuration is required to install Milvus. Usually depends on your k8s environment

**Comment by L-lei** [comment]
> @L-lei If you want to use existing pvc for minio, you can use --set minio.persistence.existingClaim=<your_pvc>. this pvc needs to be created before install.
> By default, install Milvus and Minio will automatic use default storageClass to create pvc.
> No specific hardware configuration is required to install Milvus. Usually depends on your k8s environment

OK. Thanks very much for talking to me

**Comment by L-lei** [comment]
> @L-lei 如果您想将现有 pvc 用于 minio，您可以使用 --set minio.persistence.existingClaim=<your_pvc>。这个 pvc 需要在安装前创建。
> 默认情况下，安装 Milvus，Minio 会自动使用默认的 storageClass 来创建 pvc。
> 安装 Milvus 不需要特定的硬件配置。通常取决于你的k8s环境

OK. Thanks very much for talking to me
