### ISSUE TITLE
Support logging to stdout

### ISSUE THREAD

**Issue by suvashishtha** [milvus-io/milvus-helm#207]
https://github.com/milvus-io/milvus/pull/4738/ supports logging to stdout as an option.
```
logs:
  log_to_stdout: false
  log_to_file: true
```

 But the same is not supported by helm chart it seems. Milvus version used is 1.0.0

helm chart version is 1.1.0.

**Comment by suvashishtha** [comment]
helm chart version is 1.1.0

**Comment by jeffoverflow** [comment]
Milvus 1.0.0 unsupport  logging to stdout.

**Comment by suvashishtha** [comment]
It supports. I made it worked by forking the chart and applying changes locally. Should i raise PR? Against which branch ?

**Comment by jeffoverflow** [comment]
@jeffoverflow Cool ! You can contribute chart changes based on the 1.1 branch.
