### ISSUE TITLE
One place for tolerations and nodeSelector

### ISSUE THREAD

**Issue by scipe** [milvus-io/milvus-helm#240]
Hi folks. Is there any way to place toleration and nodeSelector in only one place? Coz current helm creating a lot of deployments and it's little bit hard to change all tolerations and nodeSelectors. Also there is no pulsar-bastion in helm config so it's by default has no any toleration and nodeSelector that user can change while installing.

**Comment by LoveEachDay** [comment]
We can add a tolerations and nodeSelector config for all milvus components. I will fix this later. 

You can put the bastion config into the `values.yaml`, under the `pulsar` section like this:
```
pulsar:
  bastion:
    nodeSelector: {}
    tolerations: []
```

or pass via the `--set pulsar.bastion.nodeSelector.<key>=value` with `helm install`
