### ISSUE TITLE
Add default pulsar backlog retention policy 

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus-helm#265]
If consumer hang for some reason, user keep writing request into channel with no response, the pulsar backlog will keep increasing and my cause user running out of disk space.

by reading this document https://pulsar.apache.org/docs/zh-CN/cookbooks-retention-expiry/#backlog-quotas
I would suggest to config the policy to producer_exception and let the produce fail.

Once the consumer keep processing and catch up then the sdk can keep search

**Comment by LoveEachDay** [comment]
The default `backlogQuotaDefaultRetentionPolicy` is `producer_exception` in our milvus-helm chart.

**Comment by LoveEachDay** [comment]
We add a config to set the `backlogQuotaDefaultLimitGB` to 8GB at version 2.4.9.

**Comment by LoveEachDay** [comment]
#266
