### ISSUE TITLE
Ingress objects need to specify path type on Kubernetes 1.19+

### ISSUE THREAD

**Issue by acevenoms** [milvus-io/milvus-helm#289]
When deploying these charts to a Kubernetes 1.19+ cluster, the deployment fails with the following error:

`'failed to create resource: Ingress.extensions "milvus" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified'`

The ingress templates for Milvus are missing this field. It's required for both networking.k8s.io/v1 and extensions/v1beta1 class objects

**Comment by haorenfsa** [comment]
Thx a lot for the feedback, we'll fix this soon

**Comment by haorenfsa** [comment]
Considering add test for enable ingress and for different Kubernetes versions as well ?  @LoveEachDay @Bennu-Li

**Comment by LoveEachDay** [comment]
> Considering add test for enable ingress and for different Kubernetes versions as well ? @LoveEachDay @Bennu-Li

Yes, we'd add a compatibility test for main supported kubernetes versions.

**Comment by acevenoms** [comment]
You mean just a test in the template for the version? Or a wider test in your CI/CD? Cuz I can just fork and make a pull req for the template if you want

**Comment by acevenoms** [comment]
Oh I didn't even realized you committed a fix already. Thank you so much!
