### ISSUE TITLE
Whether custom namespaces are supported ? 

### ISSUE THREAD

**Issue by Yangstatus** [milvus-io/milvus-helm#308]
I now want to deploy the Milvus cluster through helm, but find that I cannot customize the namespace by passing parameters at the moment.

**Comment by haorenfsa** [comment]
It's supported, for example deploy `my-milvus` instance to `my-namespace` with newest version:
`helm install -n my-namespace my-milvus https://github.com/milvus-io/milvus-helm/releases/download/milvus-3.0.9/milvus-3.0.9.tgz --create-namespace`

**Comment by LoveEachDay** [comment]
There are 2 ways to deploy milvus into a specified namespace:
1. create a namespace first, then helm install <release-name> -n <namespace> milvus/milvus
2. with `--create-namespace` param: `helm install <release-name> -n <namespace> --create-namespace milvus/milvus
