### ISSUE TITLE
Not all deployment support 'image.all.pullSecrets' config

### ISSUE THREAD

**Issue by dxsooo** [milvus-io/milvus-helm#314]
Following https://artifacthub.io/packages/helm/milvus/milvus#milvus-service-configuration
I set 'image.all.pullSecrets’ to make images pulled from my private harbor ( I pulled the relative images and pushed to it)

however just the miluvs:2.0.1 related section has the field 'spec.imagePullSecret'. It seems that not all deployment support 'image.all.pullSecrets' config.

How to set imagePullSecret for the other deployments/jobs/statefulset

**Comment by haorenfsa** [comment]
If I get it correct what you mean by `other deployments/jobs/statefulset` refers to the dependencies of milvus, which are the `MinIO`, `Pulsar` & `etcd`. You can config their image by change their image configurations, which we mentioned at: The tail of the arrtifacthub document https://artifacthub.io/packages/helm/milvus/milvus#pulsar-configuration

In your particular case, values set should be:
etcd.image.pullSecrets = xxx (see https://artifacthub.io/packages/helm/bitnami/etcd, put all values under `etcd.`)
minio. imagePullSecrets = xx (see https://github.com/minio/charts/blob/main/README.md, put all values under `minio.`)

Sadly however, I just checked that the pulsar chart we're using not supports pullSecrets configurations (see: https://github.com/kafkaesque-io/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/values.yaml)  

For now you can walk around by deploy a pulsar externally & config milvus to use the external pulsar, or make your pulsar image public readable.  By the way, the pullSecret feature will not be very complex to implement, we'll try to fix this & open a PR to pulsar.

(FYI @LoveEachDay @Bennu-Li puslar helm charts we use seems not implements image pull secrets, this is a feature we should support)

**Comment by dxsooo** [comment]
OK，I will wait，thanks @haorenfsa

**Comment by haorenfsa** [comment]
@dxsooo It's merged, you can config pulsar by field `pulsar.pulsar.imagePullSecrets`

**Comment by dxsooo** [comment]
@haorenfsa it seems that not all component of pulsar respects `pulsar.pulsar.imagePullSecrets`

https://github.com/apache/pulsar-helm-chart/search?q=imagePullSecrets

And I found a PR releated https://github.com/apache/pulsar-helm-chart/pull/244

Thus I have to wait again

**Comment by haorenfsa** [comment]
milvus-helm need to update after this patch is adopted

**Comment by haorenfsa** [comment]
#244 is merged, we need to update our pulsar chart version to support it
