### ISSUE TITLE
attu service annotations

### ISSUE THREAD

**Issue by alexsstock** [milvus-io/milvus-helm#316]
The chart allows annotation of the main service.  We use this for : aws-load-balancer-internal

We would also like to deploy the attu service on an internal load balancer, using the same annotation.

**Comment by haorenfsa** [comment]
Good point. We need to add fields in `values.yaml` & add annoations to attu's service template. 
Would you like to create a PR yourself for this @alexsstock, if you've got time ?

**Comment by alexsstock** [comment]
Hi @haorenfsa , sure.  

In my testing with attu on an internal ELB, it seems to have an issue connecting to the Milvus pods.

I have tried variations of 

- $service
- $service.$namespace
- $service.$namespace.svc.cluster.local

Once I'm able to determine what's happening with networking I can submit a PR, thank you.

**Comment by alexsstock** [comment]
Apologies, this actually works great with ingress for us, and the ingress annotations are already implemented.

If you think the service annotations useful for other people for attu, I can still submit a PR.  I think they might not be needed though.
