### ISSUE TITLE
[ QUESTION ] milvus 1.1.1 on helm chart?

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [milvus-io/milvus-helm#323]
Can I install Milvus version 1.1.1 via helm? Particularly I am interested in this version: milvus:1.1.1-gpu-d061621-330cc6. Thanks

**Comment by haorenfsa** [comment]
check the 1.1 branch of this repo:  https://github.com/milvus-io/milvus-helm/tree/1.1

**Comment by ethem-kinginthenorth** [comment]
Great. Thanks
