### ISSUE TITLE
Milvus Helm is not showing any option of reusing serviceAccount in values.yaml

### ISSUE THREAD

**Issue by abhishek-ch** [milvus-io/milvus-helm#329]
Trying to use `values.yaml` for enabling/disabling features, there is no way to create/modify serviceAccount and RoleBindings.
Is there any suggestion to do that?

**Comment by haorenfsa** [comment]
Hi, milvus itself does not need extra ServiceAccount or Rolebindings, but milvus-helm uses `pulsar`, `minio`,`etcd` charts as  its default dependencies. So you can configure them with values decribed in those charts:
- configure etcd values under `etcd.xxx` (values can be found [here](https://github.com/minio/charts/blob/main/README.md))
- configure pulsar values under `pulsar.xxx` (values can be found [here](https://github.com/kafkaesque-io/pulsar-helm-chart/blob/master/helm-chart-sources/pulsar/values.yaml))
- configure minio values under `minio.xxx` (values can be found [here](https://artifacthub.io/packages/helm/bitnami/etcd))

for example you want to create `serviceAccount` for `etcd`, and you find this `serviceAccount.create` value in etcd chart docs,
so when you install it with milvus-helm you can use the field `etcd.serviceAccount.create`:
`helm install ...omit other args...  --set etcd.serviceAccount.create=true`
or write it in a values yaml:
```yaml
etcd:
  serviceAccount:
    create: true
```
