### ISSUE TITLE
external kafka not configured

### ISSUE THREAD

**Issue by danielfree** [milvus-io/milvus-helm#334]
Setting `externalKafka.enabled=true` doesn't take effect in rootcoord, the rootcoord's log still says

level=warning msg="[Failed to connect to broker.]" error="dial tcp 127.0.0.1:6650: connect: connection refused" remote_addr="pulsar://localhost:6650"

docker image: milvusdb/milvus:v2.0.2

**Comment by LoveEachDay** [comment]
If you'd use external kafka, you'd set `--set pulsar.enabled=false --set externalKafka.enabled=true` .

And milvus 2.0.2 image does not support kafka yet. If you want to have a taste before the official v2.1.0 image released, you can use image `milvusdb/milvus-dev:master-20220505-2be46a01` .
