### ISSUE TITLE
Autscaling. milvus-3.0.23 release

### ISSUE THREAD

**Issue by AndreiPaulau** [milvus-io/milvus-helm#336]
Hello!

First of all gents, thanks for such amazing product!

Earlier we've seen here https://milvus.io/docs/scaleout.md  `queryNode.autoscaling.enabled` option.
For now it's absent in values.yml, I wonder if there are any plans to move it back, since it's kind of vital options.
Forking and extending such a big chart with HPA - that's not these droids I'm looking for =)

I would be thankful for any ETA or advice
many thanks!

**Comment by AndreiPaulau** [comment]
Ok, here is an activity 👍🏻

**Comment by LoveEachDay** [comment]
@AndreiPaulau querynode an indexnode will use all the resources allocate to them. HPA doesn't make sense for our milvus querynode and indexnode. You'd better pre-caculate the memory and cpu requirement based on your vector data volume and index type. 

In future, we may implement a scaler based on tasks.

**Comment by AndreiPaulau** [comment]
Got it, thought it would work for parallel request processing.
Can be closed then
