### ISSUE TITLE
my-release-pulsar-bookie0-2转移节点后导致整个集群不可用

### ISSUE THREAD

**Issue by Zzt1993** [milvus-io/milvus-helm#354]
我把 
my-release-pulsar-bookie0
my-release-pulsar-bookie1
my-release-pulsar-bookie2
这个组件从一个k8s节点，转移到了另外一个节点上，导致整个milvus不能读写了

**Comment by Zzt1993** [comment]
storageclass后端使用的是nfs，这似乎不是因为 storageclass的原因

**Comment by AI-Mart** [comment]
> @Zzt1993 What kind of storageclass do you for pulsar bookie? Seems like you just reallocate the bookie pod into another worker nodes, but the data is missing.

不单单是数据读不出来，数据也写不进去了，不能创建索引和建表

**Comment by LoveEachDay** [comment]
@AI-Mart Could you provide logs for milvus components? Or Could you provide the error information?

> > @Zzt1993 What kind of storageclass do you for pulsar bookie? Seems like you just reallocate the bookie pod into another worker nodes, but the data is missing.
> 
> 不单单是数据读不出来，数据也写不进去了，不能创建索引和建表

**Comment by AI-Mart** [comment]
> uld you provide the error information?
> 
> > > @Zzt1993 What kind of storageclass do you for pulsar boo

具体在哪个节点看呢？

**Comment by AI-Mart** [comment]
哪个节点的哪个路径可以看到你需要的日志？

**Comment by LoveEachDay** [comment]
> > uld you provide the error information?
> > > > @Zzt1993 What kind of storageclass do you for pulsar boo
> 
> 具体在哪个节点看呢？

Use this tool: https://github.com/milvus-io/milvus/tree/master/deployments/export-log to export milvus and pulsar logs.

**Comment by Zzt1993** [comment]
上次重装了一次集群，这次又遇到了，日志太大了，如何发送到您那边呢
