### ISSUE TITLE
用的kubesphere部署milvus，出错

### ISSUE THREAD

**Issue by ruixiu** [milvus-io/milvus-helm#393]
创建失败，提示：
Error: error while running post render on files: error while running command /tmp/helm-operator/truk-reid_milvus-220_z3n3x751lj931o/helm-post-render.sh. error output: Error: map[string]interface {}(nil): yaml: unmarshal errors: line 49: mapping key "httpNumThreads" already defined at line 37 : exit status 1

**Comment by haorenfsa** [comment]
which version of `milvus-helm` & `milvus` were you installing?

> 您安装的是哪个版本的 `milvus-helm` 和 `milvus`？

**Comment by ruixiu** [comment]
刚刚搞定了：开启cluster模式，竟然需要把standalone.messageQueue设置为pulsar

**Comment by ruixiu** [comment]
milvus-helm：3.3.1 
milvus：2.2.0
只要开启pulsar就不行

**Comment by haorenfsa** [comment]
@Bennu-Li  take a look?

**Comment by Bennu-Li** [comment]
Try to delete the `httpNumThreads` param in values.yaml while installing milvus on the kubesphere.
If it still does not work, try to download the milvus-helm repo, and delete the `httpNumThreads` param in [values.yaml](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml). Then upload your local repo (milvus-helm/charts/milvus) that you changed to kubesphere to install milvus.

**Comment by ruixiu** [comment]
删除了也是一样的错误

**Comment by HuangGuSheng** [comment]
> milvus-helm：3.3.1 milvus：2.2.0 只要开启pulsar就不行

Same problem，do you solove ？
