### ISSUE TITLE
Add ability to set PodDisruptionBudget to all components

### ISSUE THREAD

**Issue by claudio-vellage** [milvus-io/milvus-helm#410]
Currently it's not possible out of the box to enable PodDisruptionBudget through the helm chart for all components, but this is required to ensure smooth node upgrades without downtime. It could happen that all pods of a specific service are running on the same node and in such a situation, without the PDB, draining the node will cause downtime.

**Comment by haorenfsa** [comment]
@claudio-vellage 
Hi, good advice. But for now milvus itself doesn't provide a mechanism to perform rolling restart without downtime for all components. So the downtime is inevitable even with the PDBs. 

And PDB has gone through an upgrade form v1beta to v1, and there's some compatity problem with earlier version of Kubernetes, which most of the users are still using.

We may add support of PDB later but for now it's not on the schedule yet. But feel free to contribute to our repo if you're willing to.
