### ISSUE TITLE
ETCD URL env cannot found

### ISSUE THREAD

**Issue by zzong2006** [milvus-io/milvus-helm#419]
In standalone mode, etcd pod(`my-release-etcd-0`) has some etcd envs such as 

```
│       ETCD_ADVERTISE_CLIENT_URLS:        http://$(MY_POD_NAME).my-release-etcd-headless.default.svc.cluster.local:2379
│       ETCD_LISTEN_CLIENT_URLS:           http://0.0.0.0:2379
│       ETCD_INITIAL_ADVERTISE_PEER_URLS:  http://$(MY_POD_NAME).my-release-etcd-headless.default.svc.cluster.local:2380
│       ETCD_LISTEN_PEER_URLS:             http://0.0.0.0:2380
│       ETCD_AUTO_COMPACTION_MODE:         revision
│       ETCD_AUTO_COMPACTION_RETENTION:    1000
│       ETCD_QUOTA_BACKEND_BYTES:          4294967296
│       ETCD_HEARTBEAT_INTERVAL:           500
│       ETCD_ELECTION_TIMEOUT:             2500
```

last 3 envs are found in values.yaml (https://github.com/milvus-io/milvus-helm/blob/614c651741fed2c9a09961b85dfdf39008cd5b03/charts/milvus/values.yaml#L496-L502), but where are these `ETCD_INITIAL_ADVERTISE_PEER_URLS` and `ETCD_ADVERTISE_CLIENT_URLS` ?

**Comment by LoveEachDay** [comment]
@zzong2006 Those environment variables are generated in the bitnami/etcd chart.

**Comment by zzong2006** [comment]
Found it. For those who have same issue, you can found in `charts/etcd/values.yaml`. I personally need to change `clusterDomain: cluster.local`.
