### ISSUE TITLE
Bundled Version of etcd using legacy PodDisruptionBudget

### ISSUE THREAD

**Issue by javajawa** [milvus-io/milvus-helm#446]
The 6.3.3 version of the `etcd` chart bundled in [charts/milvus/charts/etcd-6.3.3.tgz](https://github.com/milvus-io/milvus-helm/blob/4b32fc3143c959766ca39cac306becb03c461292/charts/milvus/charts/etcd-6.3.3.tgz) has the `PodDisruptionBudget` API hard coded to `policy/v1beta1` which was removed in Kube 1.25. This was fixed in [upstream version 6.13.4](https://github.com/bitnami/charts/commit/7f6a1952d3c2a6fe80b1f71ed60c8d6afbbd147f).

The last change to this file in this repo was a downgrade from 6.13.x back to 6.3.x: #312.
If that's not a blocker I can raise a PR to bump the chart.

**Comment by LoveEachDay** [comment]
@javajawa Good catch. For now we disable pdb by default for etcd to work around the api deprecation. It would be nice to raise a pr to bump the chart version. 

Here're some recommendations:
1. bump the etcd chart version at `charts/milvus/requirements.yaml`
2. run `helm dependency update` to regenerate the `requirements.lock` and download the new chart zip
3. bump the milvus chart version at `charts/milvus/Chart.yaml` 

After the installation tests are passed, we'll merge your pr.
