### ISSUE TITLE
always encounter 'Headless service domain does not have an IP per initial member in the cluster' in etcd when installing milvus with helm on k8s cluster

### ISSUE THREAD

**Issue by Akiqqqqqqq** [milvus-io/milvus-helm#450]
I always encounter 'Headless service domain does not have an IP per initial member in the cluster' in etcd when installing milvus with helm on k8s cluster.

<img width="1131" alt="截屏2023-06-08 11 31 15" src="https://github.com/milvus-io/milvus-helm/assets/51102894/33609b7b-c6ab-47b2-a2ec-16ecc1153faa">

before I use helm install, I had pv installed in the cluster.
<img width="1091" alt="image" src="https://github.com/milvus-io/milvus-helm/assets/51102894/4f55b791-6d60-4317-aeef-8ad813187fa1">

dont know what's going on , can anyone help me out?

**Comment by LoveEachDay** [comment]
@Akiqqqqqqq Could you confirm that the headless service for etcd is existing? Try run the following command:
```
kubectl describe service my-release-etcd-headless
```

And could you following instructions here: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
to diagnose that the headless dns name is resolved?
