### ISSUE TITLE
attu-svc template uses wrong value for loadBalancerIP field

### ISSUE THREAD

**Issue by Erzangel** [milvus-io/milvus-helm#459]
# Description of the issue

In `/charts/milvus/templates/attu-svc.yaml` ([link](https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/templates/attu-svc.yaml)), we find the following:

```yaml
  {{- if .Values.attu.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
```

The condition refers to `.Values.attu.service.loadBalancerIP`,
but the inserted value refers to `.Values.service.loadBalancerIP` which is another field, corresponding to the `loadBalancerIP` field specified for Milvus's endpoint.

This is problematic if we want to specify a different endpoint for Milvus and the Attu dashboard.

## Proposed fix

Replace the value by the same field checked in the condition:

```yaml
  {{- if .Values.attu.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.attu.service.loadBalancerIP }}
  {{- end }}
```

## Notice

This `loadBalancerIP` field will be deprecated in future API versions of Kubernetes, starting from 1.24.

The recommended alternative is to use annotations which are specific to the Load Balancer implementations, instead of `loadBalancerIP`.

Here is an example for Azure:

```yaml
annotations: {
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "1.2.3.4"
  }
```

However, this is not currently possible, as the chart does not support passing annotations to the Attu service. Maybe this could be implemented as well in order to support this feature for later Kubernetes versions?

**Comment by LoveEachDay** [comment]
@Erzangel Good catch. Could you kindly raise a pr to fix the wrong value reference?

**Comment by Erzangel** [comment]
@LoveEachDay Sure thing, here it is! #460
