### ISSUE TITLE
Milvus web admin

### ISSUE THREAD

**Issue by mausch** [milvus-io/milvus-helm#56]
Hi and thanks for this project! Our data scientists have not been this happy in a long time :-) 

I think it would be great to include https://hub.docker.com/r/milvusdb/milvus-admin as part of this repo, either as an option to the current chart or as a separate chart. What do you think?

Many thanks

**Comment by JinHai-CN** [comment]
Milvus-Admin isn't belong to LF AI. But we will consider how to combine them together more tightly.

**Comment by JinHai-CN** [comment]
@ZhifengZhang-CN Would you please help integrate milvus-admin into milvus-helm?

**Comment by ZhifengZhang-CN** [comment]
> @ZhifengZhang-CN Would you please help integrate milvus-admin into milvus-helm?

I’ll consider this matter.

**Comment by ZhifengZhang-CN** [comment]
@mausch Milvus Admin has been integrated into Milvus Helm

**Comment by mausch** [comment]
Brilliant, that was very fast, thank you!
