### ISSUE TITLE
Upgrades and WAL lock

### ISSUE THREAD

**Issue by mausch** [milvus-io/milvus-helm#79]
When upgrading Milvus from 0.9.0 to 0.9.1, kubernetes first starts a new pod with 0.9.1 before stopping 0.9.0 (as the deployment is currently set to RollingUpdate).
However the 0.9.1 pod gets stuck restarting over and over with the following error:

> Permission denied. Could not get lock.
> Milvus server exit...
> deploy_mode: single instance lock wal path failed.

So the upgrade never takes place until someone manually deletes the 0.9.0 pod

Maybe the deployment should be set to [Recreate](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment) instead?

**Comment by JinHai-CN** [comment]
One WAL directory only allows one Milvus instance read and write. You need to stop one then start another one.

**Comment by mausch** [comment]
Yep, I agree with that. What I'm proposing here is changing the Deployment in this helm chart to avoid things getting stuck because of it.

**Comment by ZhifengZhang-CN** [comment]
Thank you for your advice.

**Comment by mausch** [comment]
Works great now, thanks!
